# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\"P\n\x0f\x44\x65viceDiscovery\x12\x13\n\x0b\x64\x65vice_type\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\"W\n\rClientRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x12\n\nparameters\x18\x04 \x01(\t\"P\n\x0e\x43lientResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1c\n\x07\x64\x65vices\x18\x03 \x03(\x0b\x32\x0b.DeviceInfo\"\xc2\x01\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t\x12/\n\nattributes\x18\x06 \x03(\x0b\x32\x1b.DeviceInfo.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"4\n\rDeviceCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x12\n\nparameters\x18\x02 \x01(\t\"\xaa\x01\n\x0e\x44\x65viceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x33\n\nattributes\x18\x04 \x03(\x0b\x32\x1f.DeviceResponse.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"d\n\nSensorData\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0bsensor_type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"\\\n\x0b\x44\x65viceState\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\x12\n\nstate_json\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICEINFO_ATTRIBUTESENTRY._options = None
  _DEVICEINFO_ATTRIBUTESENTRY._serialized_options = b'8\001'
  _DEVICERESPONSE_ATTRIBUTESENTRY._options = None
  _DEVICERESPONSE_ATTRIBUTESENTRY._serialized_options = b'8\001'
  _DEVICEDISCOVERY._serialized_start=16
  _DEVICEDISCOVERY._serialized_end=96
  _CLIENTREQUEST._serialized_start=98
  _CLIENTREQUEST._serialized_end=185
  _CLIENTRESPONSE._serialized_start=187
  _CLIENTRESPONSE._serialized_end=267
  _DEVICEINFO._serialized_start=270
  _DEVICEINFO._serialized_end=464
  _DEVICEINFO_ATTRIBUTESENTRY._serialized_start=415
  _DEVICEINFO_ATTRIBUTESENTRY._serialized_end=464
  _DEVICECOMMAND._serialized_start=466
  _DEVICECOMMAND._serialized_end=518
  _DEVICERESPONSE._serialized_start=521
  _DEVICERESPONSE._serialized_end=691
  _DEVICERESPONSE_ATTRIBUTESENTRY._serialized_start=415
  _DEVICERESPONSE_ATTRIBUTESENTRY._serialized_end=464
  _SENSORDATA._serialized_start=693
  _SENSORDATA._serialized_end=793
  _DEVICESTATE._serialized_start=795
  _DEVICESTATE._serialized_end=887
# @@protoc_insertion_point(module_scope)
